pipeline {
    agent{
        docker{
            image 'python:2.7.16-slim'
            args '--user root'
        }
    }
    stages {
        stage('Install') {
            when {
                changeset '**/vote/**'
            }
            steps {
                dir('vote') {
                    echo 'Installing dependencies'
                    sh('pip install -r requirements.txt')
//                     stash name: "node_modules", includes: "**/node_modules/**" another dummy change
                }
            }
        }
        stage('Test') {
            when {
                changeset '**/vote/**'
            }

            steps {
                dir('vote') {
//                     unstash "node_modules"
                    sh('nosetest -v')
                }
            }
        }
    }
    post {
        success {
            slackSend (
                message: "Pipeline succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)",
                color: "#5afc03"
            )
        }
        failure {
            slackSend(
                message: "Pipeline failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)",
                color: "#fc0303"
            )
        }
    }
}

