pipeline {
    agent any
    tools {
        maven 'Maven 3.6.3'
    }
    stages {
        stage('Build') {
            steps {
                dir('worker') {
                    echo 'Compiling worker app'
                    sh('mvn compile')
                }
            }
        }
        stage('Test') {
            steps {
                dir('worker') {
                    sh('mvn clean test')
                }
            }
        }
        stage('Package') {
            steps {
                dir('worker') {
                    echo 'Packaging worker app'
                    sh('mvn package')
                }
            }
        }
    }
    post {
        always {
            echo "Job ${JOB_NAME}:${BUILD_ID} completed."
        }
    }
}
