pipeline {
    agent any
    tools {
        maven 'Maven 3.6.3'
    }
    stages {
        stage('Build') {
            when {
                changeset 'worker/**'
            }
            steps {
                dir('worker') {
                    echo 'Compiling worker app'
                    sh('mvn compile')
                }
            }
        }
        stage('Test') {
            when {
                changeset 'worker/**'
            }
            steps {
                dir('worker') {
                    sh('mvn clean test')
                }
            }
        }
        stage('Package') {
            when {
                branch 'master'
                changeset 'worker/**'
            }
            steps {
                dir('worker') {
                    echo 'Packaging worker app'
                    sh('mvn package -DskipTest')
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
    }
    post {
        always {
            echo "Job ${JOB_NAME}:${BUILD_ID} completed."
        }
    }
}
